[package]
name = "hijri_date"
version = "0.1.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
description = "provides functionality for conversion between hijri and gregorian calander"
license = "MIT"

[dependencies]
chrono = "0.4.5"
lazy_static = "1.0.2"
